WITH StructureData AS (
    SELECT 
        S.STR_ID AS STRUCTURE_STR_ID, -- uniqueidentifier
        S.STR_NUM AS STRUCTURE_STR_NUM, -- nvarchar
        S.REGION AS STRUCTURE_REGION, -- nvarchar
        S.STATUS AS STRUCTURE_STATUS, -- nvarchar
        S.HEIGHT AS STRUCTURE_HEIGHT, -- numeric
        S.LATITUDE AS STRUCTURE_LATITUDE, -- numeric
        S.LONGITUDE AS STRUCTURE_LONGITUDE, -- numeric
        S.OWNER AS STRUCTURE_OWNER, -- nvarchar
        S.MATERIAL AS STRUCTURE_MATERIAL, -- nvarchar
        S.PROGRESS_STATUS AS STRUCTURE_PROGRESS_STATUS, -- nvarchar
        S.GLOBALID AS STRUCTURE_GLOBALID, -- uniqueidentifier
        S.OBJECTID AS STRUCTURE_OBJECTID, -- int
        S.PMD AS STRUCTURE_PMD, -- nvarchar
        S.LINE_NAME1 AS STRUCTURE_LINE_NAME, -- nvarchar
        S.INSTALL_DATE AS STRUCTURE_INSTALL_DATE, -- datetime2
        S.LAST_INSPECT_DATE AS STRUCTURE_LAST_INSPECT_DATE, -- datetime2
        S.INSP_STATUS AS STRUCTURE_INSP_STATUS, -- nvarchar
        S.GRADE AS STRUCTURE_GRADE, -- nvarchar
        S.NUM_ARREST AS STRUCTURE_NUM_ARREST, -- int
        S.NUM_CIRCUITS AS STRUCTURE_NUM_CIRCUITS, -- nvarchar
        S.NUM_SHIELD_WIRES AS STRUCTURE_NUM_SHIELD_WIRES, -- smallint
        S.INS_MAT AS STRUCTURE_INS_MAT, -- nvarchar
        S.POLE_COUNT AS STRUCTURE_POLE_COUNT, -- smallint
        S.STEEL_FINISH AS STRUCTURE_STEEL_FINISH, -- nvarchar
        S.VOLTAGE AS STRUCTURE_VOLTAGE, -- smallint
        S.GDB_TO_DATE, -- datetime2
        ROW_NUMBER() OVER (PARTITION BY S.STR_ID ORDER BY S.GDB_TO_DATE DESC) AS RN
    FROM STRUCTURE S
)
, FilteredStructureData AS (
    SELECT * 
    FROM StructureData
    WHERE RN = 1  -- Keeping only the latest record for each STR_ID
)
, WorkOrderData AS (
    SELECT 
        WO.ID AS WORKORDER_ID, -- uniqueidentifier
        WO.WO_NAME AS WORKORDER_WO_NAME, -- nvarchar
        WO.WO_NUMBER AS WORKORDER_WO_NUMBER, -- nvarchar
        WO.WO_STATUS AS WORKORDER_WO_STATUS, -- nvarchar
        WO.ASSIGNED_DATE AS WORKORDER_ASSIGNED_DATE, -- datetime2
        WO.DUE_DATE AS WORKORDER_DUE_DATE, -- datetime2
        WO.VENDOR AS WORKORDER_VENDOR, -- nvarchar
        WO.CLIENT_ID AS WORKORDER_CLIENT_ID, -- uniqueidentifier
        WO.INSPECTION_PROGRAM_ID AS WORKORDER_INSPECTION_PROGRAM_ID, -- uniqueidentifier
        WO.FEATURE_INSPECTION_PROGRAM_ID AS WORKORDER_FEATURE_INSPECTION_PROGRAM_ID, -- uniqueidentifier
        WO.NUM_OBJECTS AS WORKORDER_NUM_OBJECTS, -- int
        WO.PARENT_WO_ID AS WORKORDER_PARENT_WO_ID -- uniqueidentifier
    FROM WORKORDER WO
)
SELECT TOP 100
    -- Structure Inspection Details
    SI.ID AS STRUCTUREINSPECTION_ID, -- uniqueidentifier
    SI.INSPECTION_DATE AS STRUCTUREINSPECTION_INSPECTION_DATE, -- datetime2
    SI.COMMENTS AS STRUCTUREINSPECTION_COMMENTS, -- nvarchar
    SI.STATUS_ID AS STRUCTUREINSPECTION_STATUS_ID, -- uniqueidentifier
    SI.ATTRIBUTE_ID AS STRUCTUREINSPECTION_ATTRIBUTE_ID, -- uniqueidentifier
    SI.PROPERTY_ID AS STRUCTUREINSPECTION_PROPERTY_ID, -- uniqueidentifier
    SI.PROPERTY_VALUE AS STRUCTUREINSPECTION_PROPERTY_VALUE, -- nvarchar
    SI.VALUE AS STRUCTUREINSPECTION_VALUE, -- nvarchar
    SI.CREATED_BY AS STRUCTUREINSPECTION_CREATED_BY, -- uniqueidentifier
    SI.CREATED_DATE AS STRUCTUREINSPECTION_CREATED_DATE, -- datetime2
    SI.MODIFIED_BY AS STRUCTUREINSPECTION_MODIFIED_BY, -- uniqueidentifier
    SI.MODIFIED_DATE AS STRUCTUREINSPECTION_MODIFIED_DATE, -- datetime2

    -- Structure Details
    SD.STRUCTURE_STR_NUM, -- nvarchar
    SD.STRUCTURE_REGION, -- nvarchar
    SD.STRUCTURE_STATUS, -- nvarchar
    SD.STRUCTURE_HEIGHT, -- numeric
    SD.STRUCTURE_LATITUDE, -- numeric
    SD.STRUCTURE_LONGITUDE, -- numeric
    SD.STRUCTURE_OWNER, -- nvarchar
    SD.STRUCTURE_MATERIAL, -- nvarchar
    SD.STRUCTURE_PROGRESS_STATUS, -- nvarchar
    SD.STRUCTURE_GLOBALID, -- uniqueidentifier
    SD.STRUCTURE_OBJECTID, -- int
    SD.STRUCTURE_PMD, -- nvarchar
    SD.STRUCTURE_LINE_NAME, -- nvarchar
    SD.STRUCTURE_INSTALL_DATE, -- datetime2
    SD.STRUCTURE_LAST_INSPECT_DATE, -- datetime2
    SD.STRUCTURE_INSP_STATUS, -- nvarchar
    SD.STRUCTURE_GRADE, -- nvarchar
    SD.STRUCTURE_NUM_ARREST, -- int
    SD.STRUCTURE_NUM_CIRCUITS, -- nvarchar
    SD.STRUCTURE_NUM_SHIELD_WIRES, -- smallint
    SD.STRUCTURE_INS_MAT, -- nvarchar
    SD.STRUCTURE_POLE_COUNT, -- smallint
    SD.STRUCTURE_STEEL_FINISH, -- nvarchar
    SD.STRUCTURE_VOLTAGE, -- smallint

    -- Inspection Status
    ISN.STATUS AS INSPECTIONSTATUS_STATUS, -- nvarchar

    -- Inspection Attributes
    IA.NAME AS INSPECTIONATTRIBUTE_NAME, -- nvarchar

    -- Inspection Attribute Property
    IAP.DESCRIPTION AS INSPECTIONATTRIBUTEPROPERTY_DESCRIPTION, -- nvarchar
    
    -- Work Order Details
    WD.WORKORDER_WO_NAME, -- nvarchar
    WD.WORKORDER_WO_NUMBER, -- nvarchar
    WD.WORKORDER_WO_STATUS, -- nvarchar
    WD.WORKORDER_ASSIGNED_DATE, -- datetime2
    WD.WORKORDER_DUE_DATE, -- datetime2
    WD.WORKORDER_VENDOR, -- nvarchar
    WD.WORKORDER_CLIENT_ID, -- uniqueidentifier
    WD.WORKORDER_INSPECTION_PROGRAM_ID, -- uniqueidentifier
    WD.WORKORDER_FEATURE_INSPECTION_PROGRAM_ID, -- uniqueidentifier
    WD.WORKORDER_NUM_OBJECTS, -- int
    WD.WORKORDER_PARENT_WO_ID -- uniqueidentifier

FROM STRUCTUREINSPECTION SI
LEFT JOIN FilteredStructureData SD ON SI.STR_ID = SD.STRUCTURE_STR_ID
LEFT JOIN INSPECTIONSTATUS ISN ON SI.STATUS_ID = ISN.ID
LEFT JOIN INSPECTIONATTRIBUTE IA ON SI.ATTRIBUTE_ID = IA.ID
LEFT JOIN INSPECTIONATTRIBUTEPROPERTY IAP ON SI.PROPERTY_ID = IAP.ID
LEFT JOIN WorkOrderData WD ON SI.WO_ID = WD.WORKORDER_ID;

