-- Table: Span_Conductor
CREATE TABLE Span_Conductor (
    GDB_ARCHIVE_OID INT NOT NULL,
    SPAN_GUID UNIQUEIDENTIFIER NULL,
    SPAN_ID NVARCHAR(255) NULL,
    COND_MAT NVARCHAR(255) NULL,
    COND_CONFIG NVARCHAR(255) NULL,
    COND_SIZE NVARCHAR(255) NULL,
    COND_INS NVARCHAR(255) NULL,
    BUNDLE_QTY NVARCHAR(255) NULL,
    INS_TYPE NVARCHAR(255) NULL,
    INS_VOLTAGE NVARCHAR(255) NULL,
    GlobalID UNIQUEIDENTIFIER NOT NULL,
    GDB_FROM_DATE DATETIME2(7) NOT NULL,
    GDB_TO_DATE DATETIME2(7) NOT NULL,
    OBJECTID INT NOT NULL,
    SW1_MAT NVARCHAR(255) NULL,
    SW1_SIZE NVARCHAR(255) NULL,
    SW1_STRAND NVARCHAR(255) NULL,
    SW2_MAT NVARCHAR(255) NULL,
    SW2_SIZE NVARCHAR(255) NULL,
    SW2_STRAND NVARCHAR(255) NULL,
    PRIMARY KEY (GDB_ARCHIVE_OID),
    UNIQUE (GlobalID)
);

-- Table: SupportStructure
CREATE TABLE SupportStructure (
    GDB_ARCHIVE_OID INT NOT NULL,
    STR_ID UNIQUEIDENTIFIER NOT NULL,
    STR_SUBTYPE NVARCHAR(255) NULL,
    STEEL_FINISH NVARCHAR(255) NULL,
    DEADEND_TYPE NVARCHAR(255) NULL,
    STR_ARM NVARCHAR(255) NULL,
    HFRAME_VEE NVARCHAR(255) NULL,
    HFRAME_KNEE NVARCHAR(255) NULL,
    X_BRACE NVARCHAR(255) NULL,
    INS_MANF NVARCHAR(255) NULL,
    MANF_DATE DATETIME2(7) NULL,
    STR_SHL NVARCHAR(255) NULL,
    SPLICE NVARCHAR(255) NULL,
    STR_GRN_L NVARCHAR(255) NULL,
    STR_GRN_D NVARCHAR(255) NULL,
    STR_GRNDH NVARCHAR(255) NULL,
    MARK_BALL NVARCHAR(255) NULL,
    BIRD_GUARDS NVARCHAR(255) NULL,
    BIRD_DETERRENT NVARCHAR(255) NULL,
    BIRD_DIVERTER NVARCHAR(255) NULL,
    ANTALGOP NVARCHAR(255) NULL,
    DANGER_SIGN NVARCHAR(255) NULL,
    CLIMBING_GUARD NVARCHAR(255) NULL,
    CORONA_RING NVARCHAR(255) NULL,
    POT_HEAD NVARCHAR(255) NULL,
    ANCHORS_NUMBER SMALLINT NULL,
    DNGWUY_NUMBER SMALLINT NULL,
    INS_NUMBER SMALLINT NULL,
    INS_TYPE NVARCHAR(255) NULL,
    STUB_NUMBER SMALLINT NULL,
    NUM_ARMS SMALLINT NULL,
    NUM_SWITCH SMALLINT NULL,
    TEXT1 NVARCHAR(255) NULL,
    TEXT2 NVARCHAR(255) NULL,
    TEXT3 NVARCHAR(255) NULL,
    TEXT4 NVARCHAR(255) NULL,
    NUMERIC1 NUMERIC(38, 8) NULL,
    NUMERIC2 NUMERIC(38, 8) NULL,
    NUMERIC3 NUMERIC(38, 8) NULL,
    DATE1 DATETIME2(7) NULL,
    DATE2 DATETIME2(7) NULL,
    GlobalID UNIQUEIDENTIFIER NOT NULL,
    GDB_FROM_DATE DATETIME2(7) NOT NULL,
    GDB_TO_DATE DATETIME2(7) NOT NULL,
    OBJECTID INT NOT NULL,
    PRIMARY KEY (GDB_ARCHIVE_OID),
    UNIQUE (GlobalID)
);

-- Table: ARM
CREATE TABLE ARM (
    ARM_ID UNIQUEIDENTIFIER NOT NULL,
    STR_ID UNIQUEIDENTIFIER NOT NULL,
    ARM_TYPE NVARCHAR(255) NOT NULL,
    GDB_FROM_DATE DATETIME2(7) NOT NULL,
    GDB_TO_DATE DATETIME2(7) NOT NULL,
    PRIMARY KEY (ARM_ID)
);

-- Table: StrFoundation
CREATE TABLE StrFoundation (
    GDB_ARCHIVE_OID INT NOT NULL,
    STR_ID UNIQUEIDENTIFIER NULL,
    FND_TYPE NVARCHAR(255) NULL,
    FND_ELEV NUMERIC(38, 8) NULL,
    FND_REVEAL NUMERIC(38, 8) NULL,
    DEPTH_ROCK NVARCHAR(255) NULL,
    GlobalID UNIQUEIDENTIFIER NOT NULL,
    GDB_FROM_DATE DATETIME2(7) NOT NULL,
    GDB_TO_DATE DATETIME2(7) NOT NULL,
    OBJECTID INT NOT NULL,
    PRIMARY KEY (GDB_ARCHIVE_OID),
    UNIQUE (GlobalID)
);

-- Table: Motor
CREATE TABLE Motor (
    MOTOR_ID UNIQUEIDENTIFIER NOT NULL,
    SWITCH_ID UNIQUEIDENTIFIER NOT NULL,
    MOTOR_TYPE NVARCHAR(255) NULL,
    CATALOG_NUMBER NVARCHAR(255) NULL,
    VOLTAGE NVARCHAR(255) NULL,
    MANUFACTURER NVARCHAR(255) NULL,
    SERIAL_NUMBER NVARCHAR(255) NULL,
    MFG_DATE DATETIME2(7) NULL,
    ROTATION NVARCHAR(255) NULL,
    INSTALL_DATE DATETIME2(7) NULL,
    REMOVAL_DATE DATETIME2(7) NULL,
    MOTOR_NUM NVARCHAR(255) NULL,
    BATTERY_DATE DATETIME2(7) NULL,
    PRIMARY KEY (MOTOR_ID)
);

-- Table: Interrupter
CREATE TABLE Interrupter (
    INTERRUPTOR_ID UNIQUEIDENTIFIER NOT NULL,
    INTERRUPTOR_NUM NVARCHAR(255) NULL,
    RATING NVARCHAR(255) NULL,
    CATALOG_NUMBER NVARCHAR(255) NULL,
    SERIAL_NUMBER NVARCHAR(255) NULL,
    INSTALL_DATE DATETIME2(7) NULL,
    MANUFACTURER NVARCHAR(255) NULL,
    GDB_FROM_DATE DATETIME2(7) NOT NULL,
    GDB_TO_DATE DATETIME2(7) NOT NULL,
    REMOVAL_DATE DATETIME2(7) NULL,
    PRIMARY KEY (INTERRUPTOR_ID)
);

-- Table: SubSwitch
CREATE TABLE SubSwitch (
    SWITCH_ID UNIQUEIDENTIFIER NOT NULL,
    INTERRUPTER_ID UNIQUEIDENTIFIER NOT NULL,
    SUBSWITCH_LOC NVARCHAR(255) NOT NULL,
    PRIMARY KEY (SWITCH_ID, INTERRUPTER_ID)
);

-- Table: Location_Inspection
CREATE TABLE Location_Inspection (
    GDB_ARCHIVE_OID INT NOT NULL,
    LOCATION_GUID UNIQUEIDENTIFIER NOT NULL,
    STREET_NUM NVARCHAR(255) NULL,
    STREET NVARCHAR(255) NULL,
    CITY NVARCHAR(255) NULL,
    STATE NVARCHAR(255) NULL,
    ZIP NVARCHAR(255) NULL,
    COUNTY NVARCHAR(255) NULL,
    OWNER NVARCHAR(255) NULL,
    OWNER_PHONE NVARCHAR(255) NULL,
    RESIDENT NVARCHAR(255) NULL,
    RESIDENT_PHONE NVARCHAR(255) NULL,
    COMMENTS NVARCHAR(255) NULL,
    ACCESS_COMMENTS NVARCHAR(255) NULL,
    ROUTE_NUMBER INT NULL,
    CUSTOMER_AT_LOC NVARCHAR(255) NULL,
    CROSS_STREET NVARCHAR(255) NULL,
    CUSTOMER_NOTIFICATION_ID UNIQUEIDENTIFIER NULL,
    DOCUMENT_ID NVARCHAR(255) NULL,
    MODIFIED_BY UNIQUEIDENTIFIER NOT NULL,
    MODIFIED_DATE DATETIME2(7) NOT NULL,
    MAIL_STREET_NUM NVARCHAR(255) NULL,
    MAIL_STREET NVARCHAR(255) NULL,
    MAIL_CITY NVARCHAR(255) NULL,
    MAIL_STATE NVARCHAR(255) NULL,
    MAIL_ZIP NVARCHAR(255) NULL,
    DAMAGE_TYPE NVARCHAR(255) NULL,
    CLAIM_AMOUNT NUMERIC(10, 2) NULL,
    CLAIM_DATE DATETIME2(7) NULL,
    PAYMENT_ISSUED_DATE DATETIME2(7) NULL,
    DAMAGE_COMMENTS NVARCHAR(255) NULL,
    DAMAGE_DATE DATETIME2(7) NULL,
    GlobalID UNIQUEIDENTIFIER NOT NULL,
    GDB_FROM_DATE DATETIME2(7) NOT NULL,
    GDB_TO_DATE DATETIME2(7) NOT NULL,
    OBJECTID INT NOT NULL,
    PRIMARY KEY (GDB_ARCHIVE_OID),
    UNIQUE (GlobalID)
);

-- Table: FacilityRelation
CREATE TABLE FacilityRelation (
    STR_ID UNIQUEIDENTIFIER NULL,
    LINEID_2 NVARCHAR(255) NULL,
    LINEID_3 NVARCHAR(255) NULL,
    LINEID_4 NVARCHAR(255) NULL,
    SWITCH_ID NVARCHAR(255) NULL,
    STATION_ID NVARCHAR(255) NULL,
    ADJACENT NVARCHAR(255) NULL
);

-- Table: InspectionStatus
CREATE TABLE InspectionStatus (
    STATUS NVARCHAR(255) NOT NULL,
    ID UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (ID)
);

-- Table: InspectionAttribute
CREATE TABLE InspectionAttribute (
    NAME NVARCHAR(122) NOT NULL,
    ID UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_InspectionAttribute PRIMARY KEY (ID)
);

-- Table: InspectionAttributeProperty
CREATE TABLE InspectionAttributeProperty (
    ID UNIQUEIDENTIFIER NOT NULL,
    NAME NVARCHAR(MAX) NULL,
    PROBLEM_CODE SMALLINT NULL,
    DESCRIPTION NVARCHAR(MAX) NULL,
    REPORTING_DESC NVARCHAR(MAX) NULL,
    CONSTRAINT PK_InspectionAttributeProperty PRIMARY KEY (ID)
);

-- Table: StructureInspection
CREATE TABLE StructureInspection (
    ID UNIQUEIDENTIFIER NOT NULL,
    WO_ID UNIQUEIDENTIFIER NOT NULL,
    STR_ID UNIQUEIDENTIFIER NOT NULL,
    ATTRIBUTE_ID UNIQUEIDENTIFIER NOT NULL,
    STATUS_ID UNIQUEIDENTIFIER NULL,
    COMMENTS NVARCHAR(MAX) NULL,
    PROPERTY_ID UNIQUEIDENTIFIER NULL,
    PROPERTY_VALUE NVARCHAR(MAX) NULL,
    INSPECTION_DATE DATETIME2(7) NOT NULL,
    CREATED_BY UNIQUEIDENTIFIER NULL,
    CREATED_DATE DATETIME2(7) NULL,
    MODIFIED_BY UNIQUEIDENTIFIER NULL,
    MODIFIED_DATE DATETIME2(7) NULL,
    [KEY] NVARCHAR(MAX) NULL,
    [VALUE] NVARCHAR(MAX) NULL,
    CONSTRAINT PK_StructureInspection PRIMARY KEY (ID)
);

-- Table: SwitchInspection
CREATE TABLE SwitchInspection (
    ID UNIQUEIDENTIFIER NOT NULL,
    WO_ID UNIQUEIDENTIFIER NOT NULL,
    Switch_ID UNIQUEIDENTIFIER NOT NULL,
    ATTRIBUTE_ID UNIQUEIDENTIFIER NOT NULL,
    STATUS_ID UNIQUEIDENTIFIER NULL,
    COMMENTS NVARCHAR(MAX) NULL,
    PROPERTY_ID UNIQUEIDENTIFIER NULL,
    PROPERTY_VALUE NVARCHAR(MAX) NULL,
    INSPECTION_DATE DATETIME2(7) NOT NULL,
    CREATED_BY UNIQUEIDENTIFIER NULL,
    CREATED_DATE DATETIME2(7) NULL,
    MODIFIED_BY UNIQUEIDENTIFIER NULL,
    MODIFIED_DATE DATETIME2(7) NULL,
    [KEY] NVARCHAR(MAX) NULL,
    [VALUE] NVARCHAR(MAX) NULL,
    CONSTRAINT PK_SwitchInspection PRIMARY KEY (ID)
);

-- Table: Grade
CREATE TABLE Grade (
    GRADE_ID UNIQUEIDENTIFIER NOT NULL,
    POLE_GUID UNIQUEIDENTIFIER NULL,
    STR_ID UNIQUEIDENTIFIER NOT NULL,
    POST_STEEL NVARCHAR(1) NULL ,
    DIAGONAL_STEEL NVARCHAR(1) NULL,
    BASE_STEEL NVARCHAR(1) NULL,
    WALL_STEEL NVARCHAR(1) NULL,
    OTHER_STEEL NVARCHAR(1) NULL,
    POST_LEG_MECHANICAL NVARCHAR(1) NULL,
    DIAGONAL_MECHANICAL NVARCHAR(1) NULL,
    BASE_MECHANICAL NVARCHAR(1) NULL,
    WALL_MECHANICAL NVARCHAR(1) NULL,
    OTHER_MECHANICAL NVARCHAR(1) NULL,
    CONCRETE_FND_GRADE NVARCHAR(1) NULL,
    COATING_GRADE NVARCHAR(1) NULL,
    BELOW_COATING NVARCHAR(3) NULL,
    ANCHOR_GRADE NVARCHAR(1) NULL,
    SOIL_CONDITIONS NVARCHAR(8) NULL,
    OVERALL_GRADE NVARCHAR(1) NULL,
    POLE_NUM NVARCHAR(MAX) NULL,
    INSPECTION_DATE DATETIME2(7) NULL,
    PERCENT_STEEL_LOSS SMALLINT NULL,
    GDB_FROM_DATE DATETIME2(7) NOT NULL,
    GDB_TO_DATE DATETIME2(7) NOT NULL,
    CONSTRAINT PK_Grade PRIMARY KEY (GRADE_ID)
);

-- Table: WorkOrder
CREATE TABLE WorkOrder (
    OBJECT_ID UNIQUEIDENTIFIER NOT NULL,
    OBJECT_TYPE UNIQUEIDENTIFIER NOT NULL,
    WO_ID UNIQUEIDENTIFIER NULL,
    ALERT_ID UNIQUEIDENTIFIER NOT NULL,
    GlobalID UNIQUEIDENTIFIER NOT NULL,
    OBJECTID INT NOT NULL,
    CONSTRAINT PK_WorkOrder PRIMARY KEY (OBJECT_ID)
);
